services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    restart: unless-stopped
    networks:
      - employee 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    restart: unless-stopped
    networks:
      - employee

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./backend/data/mongo_data:/data/db
    restart: unless-stopped
    networks:
      - employee

  
  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - employee

networks:
  employee: 
    driver: bridge

volumes:
  mongo-data: