services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    restart: unless-stopped
    networks:
      - employee 

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - CLIENT_URI=http://frontend:3000
      - JWT_SECRET=9b81a8647e4cc27659c22aa429f50a01f50b9e0e6c0023d9f2be432f87dec4fb79f4abc33d6954333a686e53b51111f9f
    restart: unless-stopped
    networks:
      - employee

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./backend/data/mongo_data:/data/db
    restart: unless-stopped
    networks:
      - employee
 
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - employee

networks:
  employee: 
    driver: bridge
